apiVersion: v1
kind: Service
metadata:
  name: custom-mysql
spec:
  selector:
    app: custom-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: minimal-website
spec:
  selector:
    app: minimal-website
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend
spec:
  selector:
    app: node-backend
  ports:
    - port: 3305
      targetPort: 3305